app_name = "pbi_integration"
app_title = "PowerBI Integration"
app_publisher = "ParaLogic"
app_description = "PowerBI Connector APIs and Tools"
app_email = "info@paralogic.io"
app_license = "gpl-3.0"
